services:
  - type: web
    name: anant-vijay-voting
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SECRET
        sync: false
